### ISSUE TITLE
Conditional waits behave dangerously by having undesired side effects.

### ISSUE THREAD

**Issue by Bia10** [Tonic-Box/TScriptsRepository#2]
Currently API functions like waitUntilIdle(), waitUntilAtTile() have nasty side effect of not allowing any change to the state of the script.

If these are currently being executed script cannot be paused/stopped and remain running until the wait condition is fulfilled. However for myriad of reasons it may not be fulfilled leaving plugin hanging in state of executing script awaiting condition which will never be fulfilled.

Either a there has to be possibility of issuing a cancelation for the awaiting operation/condition or there could be failure strategies like timeout, retry etc...

Especially consider case of being inside waitUntilIdle() and getting disconnect what should happen?
Will we ever get out of script being in executing state?

**Comment by Tonic-Box** [comment]
This should be fixed now in the latest release.
