### ISSUE TITLE
Inconsistent performance/stability for objectAction vs npcAction when using bank

### ISSUE THREAD

**Issue by Bia10** [Tonic-Box/TScriptsRepository#3]
```
 npcAction($banker, "Bank");
//objectAction($bankChest, "Use");
//objectAction($bankBooth, "Bank");
 
while (bankIsOpen() == false)
{
    tick();
}
```

Testing these combinations on multiple locations objectAction fails to open the bank commonly and ends up stuck in the while loop npcAction on the other hand nearly never results in such outcome. This demands some explanation is it a bug or just undesired feature? It should at least be noted in the documentation.

**Comment by Tonic-Box** [comment]
Please define the variables and give full script + a location in game as a test case. Without that there's not much I can test here.

**Comment by Tonic-Box** [comment]
https://i.gyazo.com/5f3ec7f0d51076d68f243ac40298f562.mp4
https://i.gyazo.com/4f647d9708a9570024e2dc1a4240e51a.mp4


I need something reproduceable in order to triage. Works fine for me. Can re open if/when you can provide a script + location to reproduce what you're talking about.
